version: '3'
services:
  webserver:
    build:
      context: web
    ports:
      - "5005:80"  # Expose port 80 from the web server to 8080 on the host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  selenium:
    build:
      context: test_automation
    depends_on:
      - webserver  # Ensure webserver is up before running the test
